[project]
name = "redis-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "grok>=6.2",
    "groq<1",
    "langchain>=1.4.3",
    "langchain-groq>=1.1.3",
    "langgraph>=0.5.0",
    "langgraph-checkpoint-redis>=0.5.2",
]

[project.scripts]
redis = "redis:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
